---
# tasks file for kibana-role
- name: Copy tar.gz Kibana from local
  ansible.builtin.copy:
    src: "{{ kibana_archive }}"
    dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    mode: 0755
    force: true
  register: get_kibana
  until: get_kibana is succeeded
  tags: kibana
- name: Create directrory for Kibana
  file:
    state: directory
    path: "{{ kibana_home }}"
  tags: kibana
- name: Extract Kibana in the installation directory
  become: true
  unarchive:
    copy: false
    src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_home }}"
    extra_opts: [--strip-components=1]
    creates: "{{ kibana_home }}/bin/kibana"
  tags:
    - skip_ansible_lint
    - kibana
- name: Set environment Kibana
  become: true
  template:
    src: templates/kib.sh.j2
    dest: /etc/profile.d/kib.sh
  tags: kibana
  